name: Build

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - master

env:
  IMG_TOOL: docker

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - name: Update version
        if: github.event_name != 'pull_request'
        run: |
          export TAG=${GITHUB_REF#refs/*/}
          export TAG=${TAG#"v"}
          echo "change the version to ${TAG}"
          jq '.version = env.TAG' package.json > package.json.new && mv package.json.new package.json
      - name: Build
        run: |
          npm i
          npm install -g @vscode/vsce
          vsce package
      - name: Publish
        if: github.event_name != 'pull_request'
        run: |
          npx ovsx publish -p ${{ secrets.OPEN_VSX_TKN }} *.vsix
      - name: Upload Release Asset
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./webhook-${{ steps.vars.outputs.version }}.vsix
          asset_name: webhook-${{ steps.vars.outputs.version }}.vsix
          asset_content_type: application/octet-stream
